services:
  - type: web
    name: rts-qa-agent
    env: python
    plan: free
    # Build the app AND the search index during the build phase
    buildCommand: "pip install -r requirements.txt && python ingest.py --build-index"
    # Then just start the web server
    startCommand: "gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: SITE_SEED_URL
        value: https://alfredorabelo.com/
      - key: SITE_ALLOWED_HOST
        value: alfredorabelo.com
      - key: CRAWL_MAX_DEPTH
        value: "2"
      - key: CACHE_DIR
        value: /opt/render/project/src/.site_cache
      # Optional: uncomment to change crawl speed
      # - key: RATE_LIMIT
      #   value: "0.5"
